export const addTraits = [
  {
    id: 1,
    busy: 'on',
    lazy: '',
    goofy: '',
    gorgeous: 'on',
    brat: 'on',
    loyal: '',
    playful: 'on',
    adventurous: 'on',
    foodie: 'on',
    snorer: '',
    crazy: 'on',
    floofy: 'on',
  },
  {
    id: 2,
    busy: 'on',
    lazy: '',
    goofy: 'on',
    gorgeous: '',
    brat: '',
    loyal: '',
    playful: 'on',
    adventurous: 'on',
    foodie: '',
    snorer: '',
    crazy: '',
    floofy: 'on',
  },
  {
    id: 3,
    busy: 'on',
    lazy: 'on',
    goofy: 'on',
    gorgeous: 'on',
    brat: 'on',
    loyal: 'on',
    playful: 'on',
    adventurous: 'on',
    foodie: 'on',
    snorer: '',
    crazy: '',
    floofy: 'on',
  },
  {
    id: 4,
    busy: 'on',
    lazy: '',
    goofy: 'on',
    gorgeous: 'on',
    brat: 'on',
    loyal: 'on',
    playful: 'on',
    adventurous: 'on',
    foodie: 'on',
    snorer: '',
    crazy: '',
    floofy: 'on',
  },
  {
    id: 5,
    busy: 'on',
    lazy: 'on',
    goofy: 'on',
    gorgeous: 'on',
    brat: '',
    loyal: 'on',
    playful: 'on',
    adventurous: '',
    foodie: 'on',
    snorer: '',
    crazy: '',
    floofy: 'on',
  },
  {
    id: 6,
    busy: 'on',
    lazy: '',
    goofy: '',
    gorgeous: 'on',
    brat: '',
    loyal: 'on',
    playful: 'on',
    adventurous: 'on',
    foodie: 'on',
    snorer: '',
    crazy: 'on',
    floofy: 'on',
  },
  {
    id: 7,
    busy: '',
    lazy: 'on',
    goofy: 'on',
    gorgeous: 'on',
    brat: 'on',
    loyal: '',
    playful: 'on',
    adventurous: 'on',
    foodie: 'on',
    snorer: '',
    crazy: 'on',
    floofy: 'on',
  },
  {
    id: 8,
    busy: 'on',
    lazy: 'on',
    goofy: 'on',
    gorgeous: 'on',
    brat: 'on',
    loyal: '',
    playful: '',
    adventurous: 'on',
    foodie: 'on',
    snorer: '',
    crazy: '',
    floofy: 'on',
  },
  {
    id: 9,
    busy: 'on',
    lazy: '',
    goofy: 'on',
    gorgeous: 'on',
    brat: '',
    loyal: '',
    playful: 'on',
    adventurous: 'on',
    foodie: '',
    snorer: 'on',
    crazy: 'on',
    floofy: 'on',
  },
  {
    id: 10,
    busy: 'on',
    lazy: 'on',
    goofy: '',
    gorgeous: 'on',
    brat: 'on',
    loyal: 'on',
    playful: 'on',
    adventurous: '',
    foodie: 'on',
    snorer: '',
    crazy: '',
    floofy: 'on',
  },
  {
    id: 11,
    busy: 'on',
    lazy: 'on',
    goofy: 'on',
    gorgeous: 'on',
    brat: '',
    loyal: '',
    playful: 'on',
    adventurous: 'on',
    foodie: 'on',
    snorer: '',
    crazy: '',
    floofy: 'on',
  },
  {
    id: 12,
    busy: 'on',
    lazy: 'on',
    goofy: 'on',
    gorgeous: 'on',
    brat: '',
    loyal: 'on',
    playful: 'on',
    adventurous: 'on',
    foodie: 'on',
    snorer: '',
    crazy: '',
    floofy: 'on',
  },
  {
    id: 13,
    busy: 'on',
    lazy: 'on',
    goofy: 'on',
    gorgeous: 'on',
    brat: '',
    loyal: '',
    playful: 'on',
    adventurous: 'on',
    foodie: 'on',
    snorer: '',
    crazy: '',
    floofy: 'on',
  },
  {
    id: 14,
    busy: 'on',
    lazy: 'on',
    goofy: 'on',
    gorgeous: 'on',
    brat: '',
    loyal: '',
    playful: 'on',
    adventurous: 'on',
    foodie: 'on',
    snorer: '',
    crazy: '',
    floofy: 'on',
  },
  {
    id: 15,
    busy: 'on',
    lazy: 'on',
    goofy: 'on',
    gorgeous: 'on',
    brat: 'on',
    loyal: '',
    playful: 'on',
    adventurous: 'on',
    foodie: '',
    snorer: '',
    crazy: '',
    floofy: 'on',
  },
  {
    id: 16,
    busy: 'on',
    lazy: 'on',
    goofy: 'on',
    gorgeous: 'on',
    brat: '',
    loyal: '',
    playful: 'on',
    adventurous: 'on',
    foodie: 'on',
    snorer: '',
    crazy: '',
    floofy: 'on',
  },
  {
    id: 17,
    busy: 'on',
    lazy: 'on',
    goofy: 'on',
    gorgeous: 'on',
    brat: 'on',
    loyal: '',
    playful: 'on',
    adventurous: 'on',
    foodie: '',
    snorer: '',
    crazy: '',
    floofy: 'on',
  },
]

export async function seed(knex) {
  await knex('traits').insert(addTraits)
}
