export const addTraits = [
  {
    id: 1,
    busy: 'true',
    lazy: 'false',
    goofy: 'false',
    gorgeous: 'true',
    brat: 'true',
    loyal: 'false',
    playful: 'true',
    adventurous: 'true',
    foodie: 'true',
    snorer: 'false',
    crazy: 'true',
    floofy: 'true',
  },
  {
    id: 2,
    busy: 'true',
    lazy: 'false',
    goofy: 'true',
    gorgeous: 'false',
    brat: 'false',
    loyal: 'false',
    playful: 'true',
    adventurous: 'true',
    foodie: 'false',
    snorer: 'false',
    crazy: 'false',
    floofy: 'true',
  },
  {
    id: 3,
    busy: 'true',
    lazy: 'true',
    goofy: 'true',
    gorgeous: 'true',
    brat: 'true',
    loyal: 'true',
    playful: 'true',
    adventurous: 'true',
    foodie: 'true',
    snorer: 'false',
    crazy: 'false',
    floofy: 'true',
  },
  {
    id: 4,
    busy: 'true',
    lazy: 'false',
    goofy: 'true',
    gorgeous: 'true',
    brat: 'true',
    loyal: 'true',
    playful: 'true',
    adventurous: 'true',
    foodie: 'true',
    snorer: 'false',
    crazy: 'false',
    floofy: 'true',
  },
  {
    id: 5,
    busy: 'true',
    lazy: 'true',
    goofy: 'true',
    gorgeous: 'true',
    brat: 'false',
    loyal: 'true',
    playful: 'true',
    adventurous: 'false',
    foodie: 'true',
    snorer: 'false',
    crazy: 'false',
    floofy: 'true',
  },
  {
    id: 6,
    busy: 'true',
    lazy: 'false',
    goofy: 'false',
    gorgeous: 'true',
    brat: 'false',
    loyal: 'true',
    playful: 'true',
    adventurous: 'true',
    foodie: 'true',
    snorer: 'false',
    crazy: 'true',
    floofy: 'true',
  },
  {
    id: 7,
    busy: 'false',
    lazy: 'true',
    goofy: 'true',
    gorgeous: 'true',
    brat: 'true',
    loyal: 'false',
    playful: 'true',
    adventurous: 'true',
    foodie: 'true',
    snorer: 'false',
    crazy: 'true',
    floofy: 'true',
  },
  {
    id: 8,
    busy: 'true',
    lazy: 'true',
    goofy: 'true',
    gorgeous: 'true',
    brat: 'true',
    loyal: 'false',
    playful: 'false',
    adventurous: 'true',
    foodie: 'true',
    snorer: 'false',
    crazy: 'false',
    floofy: 'true',
  },
  {
    id: 9,
    busy: 'true',
    lazy: 'false',
    goofy: 'true',
    gorgeous: 'true',
    brat: 'false',
    loyal: 'false',
    playful: 'true',
    adventurous: 'true',
    foodie: 'false',
    snorer: 'true',
    crazy: 'true',
    floofy: 'true',
  },
  {
    id: 10,
    busy: 'true',
    lazy: 'true',
    goofy: 'false',
    gorgeous: 'true',
    brat: 'true',
    loyal: 'true',
    playful: 'true',
    adventurous: 'false',
    foodie: 'true',
    snorer: 'false',
    crazy: 'false',
    floofy: 'true',
  },
  {
    id: 11,
    busy: 'true',
    lazy: 'true',
    goofy: 'true',
    gorgeous: 'true',
    brat: 'false',
    loyal: 'false',
    playful: 'true',
    adventurous: 'true',
    foodie: 'true',
    snorer: 'false',
    crazy: 'false',
    floofy: 'true',
  },
  {
    id: 12,
    busy: 'true',
    lazy: 'true',
    goofy: 'true',
    gorgeous: 'true',
    brat: 'false',
    loyal: 'true',
    playful: 'true',
    adventurous: 'true',
    foodie: 'true',
    snorer: 'false',
    crazy: 'false',
    floofy: 'true',
  },
  {
    id: 13,
    busy: 'true',
    lazy: 'true',
    goofy: 'true',
    gorgeous: 'true',
    brat: 'false',
    loyal: 'false',
    playful: 'true',
    adventurous: 'true',
    foodie: 'true',
    snorer: 'false',
    crazy: 'false',
    floofy: 'true',
  },
  {
    id: 14,
    busy: 'true',
    lazy: 'true',
    goofy: 'true',
    gorgeous: 'true',
    brat: 'false',
    loyal: 'false',
    playful: 'true',
    adventurous: 'true',
    foodie: 'true',
    snorer: 'false',
    crazy: 'false',
    floofy: 'true',
  },
  {
    id: 15,
    busy: 'true',
    lazy: 'true',
    goofy: 'true',
    gorgeous: 'true',
    brat: 'true',
    loyal: 'false',
    playful: 'true',
    adventurous: 'true',
    foodie: 'false',
    snorer: 'false',
    crazy: 'false',
    floofy: 'true',
  },
  {
    id: 16,
    busy: 'true',
    lazy: 'true',
    goofy: 'true',
    gorgeous: 'true',
    brat: 'false',
    loyal: 'false',
    playful: 'true',
    adventurous: 'true',
    foodie: 'true',
    snorer: 'false',
    crazy: 'false',
    floofy: 'true',
  },
  {
    id: 17,
    busy: 'true',
    lazy: 'true',
    goofy: 'true',
    gorgeous: 'true',
    brat: 'true',
    loyal: 'false',
    playful: 'true',
    adventurous: 'true',
    foodie: 'false',
    snorer: 'false',
    crazy: 'false',
    floofy: 'true',
  },
]

export async function seed(knex) {
  await knex('traits').insert(addTraits)
}
