export const addPets = [
  {
    id: 1,
    owner_id: 1,
    pet_name: 'Pepper',
    image: 'pepper.JPG',
    dob: '2021-12-01',
    gender: 'Girlie pop',
    breed: 'Maltese',
    species: 'Dog',
    bio: "I love long walks, belly rubs, and chasing after toys. I'm always up for an adventure, whether it's exploring the outdoors or snuggling on the couch. I bring joy and laughter to everyone I meet, and I'm the perfect partner in crime for any fun!",
    trait_id: 1,
  },
  {
    id: 2,
    owner_id: 2,
    pet_name: 'Obi',
    image: 'obi.png',
    dob: '2021-02-07',
    gender: 'Boy',
    breed: 'Border Collie',
    species: 'Dog',
    bio: "I love long walks, belly rubs, and chasing after toys. I'm always up for an adventure, whether it's exploring the outdoors or snuggling on the couch. I bring joy and laughter to everyone I meet, and I'm the perfect partner in crime for any fun!",
    trait_id: 2,
  },
  {
    id: 3,
    owner_id: 3,
    pet_name: 'Luna',
    image: 'luna.jpg',
    dob: '2019-11-13',
    gender: 'Girl',
    breed: 'Cat',
    species: 'Cat',
    bio: 'I am a curious and playful cat who loves climbing and exploring new spaces. My purrs are as soothing as a lullaby, and I enjoy napping in sunny spots and getting cozy in warm blankets. I’m a true companion with a touch of mischief.',
    trait_id: 3,
  },
  {
    id: 4,
    owner_id: 3,
    pet_name: 'Django',
    image: 'django.jpg',
    dob: '2019-11-13',
    gender: 'Boy',
    breed: 'Cat',
    species: 'Cat',
    bio: 'I am a curious and playful cat who loves climbing and exploring new spaces. My purrs are as soothing as a lullaby, and I enjoy napping in sunny spots and getting cozy in warm blankets. I’m a true companion with a touch of mischief.',
    trait_id: 4,
  },
  {
    id: 5,
    owner_id: 4,
    pet_name: 'Pixel',
    image: 'pixel.jpg',
    dob: '2019-11-13',
    gender: 'Girl',
    breed: 'Cat',
    species: 'Cat',
    bio: 'I am a curious and playful cat who loves climbing and exploring new spaces. My purrs are as soothing as a lullaby, and I enjoy napping in sunny spots and getting cozy in warm blankets. I’m a true companion with a touch of mischief.',
    trait_id: 5,
  },
  {
    id: 6,
    owner_id: 4,
    pet_name: 'Miso',
    image: 'miso.jpg',
    dob: '2022-01-18',
    gender: 'Boy',
    breed: 'Cutie',
    species: 'Cat',
    bio: 'I am a loyal and intelligent cat with a strong protective instinct. My training and obedience make me a reliable companion. I enjoy challenging activities like agility training and playing fetch, and I’m always ready to guard and protect my loved ones.',
    trait_id: 6,
  },
  {
    id: 7,
    owner_id: 5,
    pet_name: 'Starsky',
    image: 'starsky.jpg',
    dob: '2020-05-22',
    gender: 'Boy',
    breed: 'Meow meow',
    species: 'Cat',
    bio: 'I’m an energetic and friendly cat who loves to fetch and play with everyone. My wagging tail and happy demeanor make me a hit at the park. I thrive on companionship and am always eager to make new friends and join in on adventures.',
    trait_id: 7,
  },
  {
    id: 8,
    owner_id: 6,
    pet_name: 'Bella',
    image: 'bella.jpg',
    dob: '2017-03-14',
    gender: 'Girlie pop',
    breed: 'Labrador',
    species: 'Dog',
    bio: 'I’m a unique and affectionate gorgeous gorgeous girl with a love for warmth and cuddles. My playful antics and loving nature make me a joy to be around. I enjoy snuggling up with my human and being the center of attention.',
    trait_id: 8,
  },
  {
    id: 9,
    owner_id: 7,
    pet_name: 'Tess',
    image: 'tess.jpeg',
    dob: '2023-03-09',
    gender: 'Girlie pop',
    breed: 'Bordie collie',
    species: 'Dog',
    bio: 'I’m a whirlwind of energy, always on the move and ready for my next big adventure. From chasing frisbees at lightning speed to orchestrating the ultimate backyard obstacle course, I bring a level of enthusiasm and excitement to everything I do. I’m not just a dog; I’m a bundle of joy that turns every day into a thrilling escapade. My herding instincts keep me busy, and my playful spirit ensures there’s never a dull moment.',
    trait_id: 9,
  },
  {
    id: 10,
    owner_id: 8,
    pet_name: 'Ginger',
    image: 'ginger.jpg',
    dob: '2018-09-10',
    gender: 'Girl',
    breed: 'Maine Coon',
    species: 'Cat',
    bio: 'With my fluffy fur and gentle nature, I’m the queen of the household. I love lounging on high perches and observing everything below. My calm demeanor and soft purrs bring a sense of peace to my home. I enjoy being pampered and loved.',
    trait_id: 10,
  },
  {
    id: 11,
    owner_id: 9,
    pet_name: 'Luna',
    image: 'luna.jpg',
    dob: '2021-07-03',
    gender: 'Girl',
    breed: 'Husky',
    species: 'Dog',
    bio: 'With my striking blue eyes and boundless energy, I’m always up for a run or hike. My playful nature and affectionate personality make me a favorite among friends and family. I thrive on outdoor activities and enjoy being the center of attention.',
    trait_id: 11,
  },
  {
    id: 12,
    owner_id: 10,
    pet_name: 'Bella',
    image: 'bella.jpg',
    dob: '2019-08-15',
    gender: 'Girl',
    breed: 'Cocker Spaniel',
    species: 'Dog',
    bio: 'I’m a sweet and gentle dog with a love for playtime and affection. My floppy ears and loving eyes make me an adorable companion. I enjoy running around and playing with my favorite toys, and I’m always ready to cuddle up after a day of fun.',
    trait_id: 12,
  },
  {
    id: 13,
    owner_id: 11,
    pet_name: 'Thumper',
    image: 'thumper.jpg',
    dob: '2022-05-30',
    gender: 'Boy',
    breed: 'Holland Lop',
    species: 'Rabbit',
    bio: 'I’m a cute and friendly rabbit with a love for hopping around and munching on fresh veggies. My soft fur and gentle personality make me a wonderful companion for anyone looking for a bit of extra fluff in their life. I enjoy cozy burrows and gentle petting.',
    trait_id: 13,
  },
  {
    id: 14,
    owner_id: 12,
    pet_name: 'Star',
    image: 'star.jpg',
    dob: '2018-04-15',
    gender: 'Girl',
    breed: 'Arabian',
    species: 'Horse',
    bio: 'I’m a majestic and graceful horse with a love for running in the open fields. My strong and elegant presence makes me a sight to behold. I enjoy long rides and the bond I share with my rider. I’m loyal and spirited, always ready for an adventure.',
    trait_id: 14,
  },
  {
    id: 15,
    owner_id: 13,
    pet_name: 'Bubbles',
    image: 'bubbles.jpg',
    dob: '2021-11-05',
    gender: 'Boy',
    breed: 'Betta Fish',
    species: 'Fish',
    bio: 'I’m a vibrant and lively fish with beautiful fins and an elegant swim. I enjoy a peaceful tank environment and bring a touch of serenity to any room. My colorful scales and graceful movements make me a relaxing companion to watch.',
    trait_id: 15,
  },
  {
    id: 16,
    owner_id: 14,
    pet_name: 'Zog',
    image: 'zog.jpg',
    dob: '2024-01-01',
    gender: 'Alien',
    breed: 'Xenon',
    species: 'Alien',
    bio: 'I’m a friendly and curious alien from a distant galaxy. My unique appearance and otherworldly traits make me a fascinating companion. I enjoy exploring new environments and learning about Earth’s culture. I bring a touch of the extraordinary to everyday life.',
    trait_id: 16,
  },
  {
    id: 17,
    owner_id: 15,
    pet_name: 'Chirpy',
    image: 'chirpy.jpg',
    dob: '2022-08-25',
    gender: 'Girl',
    breed: 'Cockatiel',
    species: 'Bird',
    bio: 'I’m a cheerful and vocal bird with a love for singing and interacting with my human friends. My bright plumage and playful personality make me a delightful companion. I enjoy whistling tunes and playing with toys. My presence adds a bit of melody to life.',
    trait_id: 17,
  },
]

export async function seed(knex) {
  await knex('pets').insert(addPets)
}
