export const addPets = [
  {
    id: 1,
    owner_id: 'auth0|66e50f691c13e2abcc0bdf91',
    pet_name: 'Pepper',
    image: 'pepper.webp',
    dob: '2021-12-01',
    gender: 'Girlie pop',
    breed: 'Maltese',
    species: 'Dog',
    bio: 'I’m Pepper, the Maltese with a personality that’s as spicy as my name! My hobbies include performing the ‘zoomies’ at 3 AM and pretending my toys are top-secret spy gadgets. I may be small, but I’ve got big dreams—mostly involving endless belly rubs and making my humans laugh with my playful antics. I’m your go-to gal for a good time and an even better cuddle session!',
    trait_id: 1,
  },
  {
    id: 2,
    owner_id: 'auth0|123',
    pet_name: 'Obi',
    image: 'obi.webp',
    dob: '2021-02-07',
    gender: 'Boy',
    breed: 'Border Collie',
    species: 'Dog',
    bio: 'Meet Obi, the Border Collie who’s always on a quest for the next great adventure! My life motto? ‘Why sit still when you can sprint?’ When I’m not busy herding invisible sheep or concocting new ways to catch the frisbee mid-air, I’m plotting my next prank on my human. Keep up if you can—I promise, it’ll be a wild ride!',
    trait_id: 2,
  },
  {
    id: 3,
    owner_id: 'auth0|66d68c678f5438f35cec79c2',
    pet_name: 'Luna',
    image: 'luna.webp',
    dob: '2019-11-13',
    gender: 'Girl',
    breed: 'Cat',
    species: 'Cat',
    bio: 'Hey there, I’m Luna! I’m the cat who’s got more curiosity than a catnip store and more mischief than a kitten with a laser pointer. My hobbies include perfecting my stealthy pounce and making sure no sunny spot is left un-napped. Don’t let my sweet purrs fool you—I’m a tiny troublemaker with a penchant for drama!',
    trait_id: 3,
  },
  {
    id: 4,
    owner_id: 'auth0|66d68c678f5438f35cec79c2',
    pet_name: 'Django',
    image: 'django.webp',
    dob: '2019-11-13',
    gender: 'Boy',
    breed: 'Cat',
    species: 'Cat',
    bio: 'I’m Django, the cat who believes every day should be an adventure, preferably one that ends with a nap in a cozy corner. If you hear mysterious noises at night, that’s probably me trying to figure out how to open the treat cupboard. My motto? ‘Why be a boring cat when you can be a cat with a flair for the dramatic?’',
    trait_id: 4,
  },
  {
    id: 5,
    owner_id: 'github|171200457',
    pet_name: 'Pixel',
    image: 'pixel.webp',
    dob: '2019-11-13',
    gender: 'Girl',
    breed: 'Cat',
    species: 'Cat',
    bio: 'Pixel here, your pint-sized explorer with a heart as big as my curiosity! I’m on a mission to discover every nook and cranny of the house, and if you’ve misplaced something, don’t worry—I’m on it. Between my playful pounces and dramatic sprawls in sunbeams, I’m here to bring a touch of whimsy to your life!',
    trait_id: 5,
  },
  {
    id: 6,
    owner_id: 'github|171200457',
    pet_name: 'Miso',
    image: 'miso.webp',
    dob: '2022-01-18',
    gender: 'Boy',
    breed: 'Cutie',
    species: 'Cat',
    bio: 'Hello, I’m Miso, the cat who takes ‘loyal companion’ to a whole new level. I’m like a four-legged secret agent—always alert and ready for action, whether it’s a game of fetch or an intense round of agility training. I might look like a cute cuddle bug, but don’t let that fool you; I’m a dedicated protector and a playful prankster!',
    trait_id: 6,
  },
  {
    id: 7,
    owner_id: 'auth0|66e4c67a85ce6c31049fb8a6',
    pet_name: 'Starsky',
    image: 'starsky.webp',
    dob: '2020-05-22',
    gender: 'Boy',
    breed: 'Meow meow',
    species: 'Cat',
    bio: 'Starsky, reporting for duty! I’m the cat who’s always up for a game of fetch, no matter how many times I have to chase that toy. My tail’s a wagging, my spirit’s soaring, and my favorite pastime is making sure everyone knows how friendly and fun I am. If you’re looking for a partner in play and a friend for life, I’m your guy!',
    trait_id: 7,
  },
  {
    id: 8,
    owner_id: 'auth0|4',
    pet_name: 'Bella',
    image: 'bella.webp',
    dob: '2017-03-14',
    gender: 'Girlie pop',
    breed: 'Labrador',
    species: 'Dog',
    bio: 'Hi, I’m Bella, your friendly neighborhood Labrador with a tail that’s practically a metronome of happiness! I live for belly rubs, the occasional snack, and being the center of attention. If you’re looking for someone to help you find your lost socks or just snuggle up for a movie night, I’m your go-to girl!',
    trait_id: 8,
  },
  {
    id: 9,
    owner_id: 'auth0|5',
    pet_name: 'Tess',
    image: 'tess.webp',
    dob: '2023-03-09',
    gender: 'Girlie pop',
    breed: 'Bordie collie',
    species: 'Dog',
    bio: 'I’m a whirlwind of energy, always on the move and ready for my next big adventure. From chasing frisbees at lightning speed to orchestrating the ultimate backyard obstacle course, I bring a level of enthusiasm and excitement to everything I do. I’m not just a dog; I’m a bundle of joy that turns every day into a thrilling escapade. My herding instincts keep me busy, and my playful spirit ensures there’s never a dull moment.',
    trait_id: 9,
  },
  {
    id: 10,
    owner_id: 'auth0|6',
    pet_name: 'Ginger',
    image: 'ginger.webp',
    dob: '2018-09-10',
    gender: 'Girl',
    breed: 'Maine Coon',
    species: 'Cat',
    bio: 'With my fluffy fur and gentle nature, I’m the queen of the household. I love lounging on high perches and observing everything below. My calm demeanor and soft purrs bring a sense of peace to my home. I enjoy being pampered and loved.',
    trait_id: 10,
  },
  {
    id: 11,
    owner_id: 'auth0|7',
    pet_name: 'Luna',
    image: 'luna-2.webp',
    dob: '2021-07-03',
    gender: 'Girl',
    breed: 'Husky',
    species: 'Dog',
    bio: 'With my striking blue eyes and boundless energy, I’m always up for a run or hike. My playful nature and affectionate personality make me a favorite among friends and family. I thrive on outdoor activities and enjoy being the center of attention.',
    trait_id: 11,
  },
  {
    id: 12,
    owner_id: 'auth0|8',
    pet_name: 'Bella',
    image: 'bella-2.webp',
    dob: '2019-08-15',
    gender: 'Girl',
    breed: 'Cocker Spaniel',
    species: 'Dog',
    bio: 'I’m a sweet and gentle dog with a love for playtime and affection. My floppy ears and loving eyes make me an adorable companion. I enjoy running around and playing with my favorite toys, and I’m always ready to cuddle up after a day of fun.',
    trait_id: 12,
  },
  {
    id: 13,
    owner_id: 'auth0|9',
    pet_name: 'Thumper',
    image: 'thumper.webp',
    dob: '2022-05-30',
    gender: 'Boy',
    breed: 'Holland Lop',
    species: 'Rabbit',
    bio: 'I’m a cute and friendly rabbit with a love for hopping around and munching on fresh veggies. My soft fur and gentle personality make me a wonderful companion for anyone looking for a bit of extra fluff in their life. I enjoy cozy burrows and gentle petting.',
    trait_id: 13,
  },
  {
    id: 14,
    owner_id: 'auth0|10',
    pet_name: 'Star',
    image: 'star.webp',
    dob: '2018-04-15',
    gender: 'Girl',
    breed: 'Arabian',
    species: 'Horse',
    bio: 'I’m a majestic and graceful horse with a love for running in the open fields. My strong and elegant presence makes me a sight to behold. I enjoy long rides and the bond I share with my rider. I’m loyal and spirited, always ready for an adventure.',
    trait_id: 14,
  },
  {
    id: 15,
    owner_id: 'auth0|11',
    pet_name: 'Bubbles',
    image: 'bubbles.webp',
    dob: '2021-11-05',
    gender: 'Boy',
    breed: 'Betta Fish',
    species: 'Fish',
    bio: 'I’m a vibrant and lively fish with beautiful fins and an elegant swim. I enjoy a peaceful tank environment and bring a touch of serenity to any room. My colorful scales and graceful movements make me a relaxing companion to watch.',
    trait_id: 15,
  },
  {
    id: 16,
    owner_id: 'auth0|12',
    pet_name: 'Zog',
    image: 'zog.webp',
    dob: '2024-01-01',
    gender: 'Alien',
    breed: 'Xenon',
    species: 'Alien',
    bio: 'I’m a friendly and curious alien from a distant galaxy. My unique appearance and otherworldly traits make me a fascinating companion. I enjoy exploring new environments and learning about Earth’s culture. I bring a touch of the extraordinary to everyday life.',
    trait_id: 16,
  },
  {
    id: 17,
    owner_id: 'auth0|13',
    pet_name: 'Chirpy',
    image: 'chirpy.webp',
    dob: '2022-08-25',
    gender: 'Girl',
    breed: 'Cockatiel',
    species: 'Bird',
    bio: 'I’m a cheerful and vocal bird with a love for singing and interacting with my human friends. My bright plumage and playful personality make me a delightful companion. I enjoy whistling tunes and playing with toys. My presence adds a bit of melody to life.',
    trait_id: 17,
  },
]

export async function seed(knex) {
  await knex('pets').insert(addPets)
}
