export const addEvents = [
  {
    id: 1,
    title: 'Food Truck Night in Howick',
    date: '2024-10-03',
    time: '17:00',
    location: 'Lloyd Elsmore Park, Sir Lloyd Drive, Auckland',
    description:
      '🍔🌮 Experience the Best of Street Food at Howick’s Ultimate Food Truck Night! 🚚🎉 Join us in Howick for an exciting Food Truck Night that promises a feast for all your senses! Get ready to dive into a world of flavors as the best food trucks in town come together to serve up mouthwatering dishes that will leave you craving more.',
    event_image: 'event-1.webp',
    event_website:
      'https://www.eventfinda.co.nz/2024/food-trucks-in-howick/auckland/pakuranga',
    audience: 'Anyone!',
    creator_id: 1,
  },
  {
    id: 2,
    title: 'Paws & Pints: Dog-Friendly Brewery Tour',
    date: '2024-10-07',
    time: '15:00',
    location: 'The Hoppy Hound Brewery, 123 Bark Avenue, Dogtown',
    description:
      '🍺🐶 Grab your furry friend and join us for Paws & Pints, a brewery tour where dogs are more than welcome! Enjoy craft beers, dog-friendly treats, and live music while mingling with fellow pet lovers.',
    event_image: 'event-2.webp',
    event_website: 'https://www.example.com/paws-and-pints',
    audience: 'Dog Owners',
    creator_id: 2,
  },
  {
    id: 3,
    title: 'Equestrian Gala: Horses & Harmony',
    date: '2024-10-11',
    time: '18:00',
    location: 'Green Meadows Riding Club, 456 Gallop Lane, Equestriatown',
    description:
      '🏇✨ Join us for an elegant evening at the Equestrian Gala! Enjoy dressage performances, horse demonstrations, and a silent auction to benefit equine charities. Perfect for horse enthusiasts and their families.',
    event_image: 'event-3.webp',
    event_website: 'https://www.example.com/equestrian-gala',
    audience: 'Horse Lovers',
    creator_id: 3,
  },
  {
    id: 4,
    title: 'Feline Fun Fest: Cat Yoga & More!',
    date: '2024-10-17',
    time: '10:00',
    location: 'Purrfect Yoga Studio, 789 Meow Road, Catville',
    description:
      '🧘‍♂️🐱 Stretch, relax, and play with adoptable cats at our Cat Yoga session! Enjoy guided yoga with feline friends, cat-themed crafts, and a meet-and-greet with local shelters.',
    event_image: 'event-4.webp',
    event_website: 'https://www.example.com/feline-fun-fest',
    audience: 'Cat Lovers',
    creator_id: 4,
  },
  {
    id: 5,
    title: 'Pet Costume Parade',
    date: '2024-10-22',
    time: '14:00',
    location: 'Central Park, 321 Parade Street, Pet City',
    description:
      '🎃🐾 Dress up your pets and join us for a spooktacular Pet Costume Parade! Prizes for the best costumes, pet-friendly treats, and plenty of fun for pets and their humans. Don’t miss this Halloween-themed event!',
    event_image: 'event-5.webp',
    event_website: 'https://www.example.com/pet-costume-parade',
    audience: 'Pet Owners',
    creator_id: 5,
  },
  {
    id: 6,
    title: 'Birdwatching & Beaks Picnic',
    date: '2024-11-05',
    time: '11:00',
    location: 'Sunnyvale Park, 567 Wing Street, Birdtown',
    description:
      '🦜🌳 Enjoy a day of birdwatching with fellow avian enthusiasts! Bring your binoculars, a picnic lunch, and learn about local bird species while your feathered friends enjoy a treat-filled picnic.',
    event_image: 'event-6.webp',
    event_website: 'https://www.example.com/birdwatching-picnic',
    audience: 'Bird Lovers',
    creator_id: 6,
  },
  {
    id: 7,
    title: 'Dog Agility Competition',
    date: '2024-11-12',
    time: '09:00',
    location: 'Agility Arena, 890 Jump Road, Dogtown',
    description:
      '🏅🐕 Watch talented dogs navigate challenging agility courses in this exciting competition! Perfect for dogs of all skill levels, with awards for speed, precision, and best overall performance.',
    event_image: 'event-7.webp',
    event_website: 'https://www.example.com/dog-agility-competition',
    audience: 'Dog Owners and Enthusiasts',
    creator_id: 7,
  },
  {
    id: 8,
    title: 'Hamster Wheel Derby',
    date: '2024-11-19',
    time: '16:00',
    location: 'Tiny Pets Park, 234 Squeak Lane, Hamsterville',
    description:
      '🚴🐹 Cheer on hamsters as they race in their very own wheel derby! With fun races, obstacle courses, and a chance to meet local hamster enthusiasts, this event is a must for small pet lovers.',
    event_image: 'event-8.webp',
    event_website: 'https://www.example.com/hamster-wheel-derby',
    audience: 'Hamster Owners and Enthusiasts',
    creator_id: 8,
  },
  {
    id: 9,
    title: 'Pet Fitness Expo',
    date: '2024-11-26',
    time: '10:00',
    location: 'Fitness Park, 345 Healthy Way, Pet City',
    description:
      '💪🐾 Join us at the Pet Fitness Expo to discover the best ways to keep your pets active and healthy! Featuring fitness demos, pet exercise classes, and expert talks on pet wellness.',
    event_image: 'event-9.webp',
    event_website: 'https://www.example.com/pet-fitness-expo',
    audience: 'Pet Owners and Health Enthusiasts',
    creator_id: 9,
  },
  {
    id: 10,
    title: 'Bunny Bonding Brunch',
    date: '2024-12-02',
    time: '11:00',
    location: "Fluffy's Bistro, 678 Carrot Lane, Bunnyville",
    description:
      '🥕🐇 Enjoy a delightful brunch while bonding with your bunnies and other rabbit lovers! The event features bunny-friendly foods, educational talks on rabbit care, and a bunny play area.',
    event_image: 'event-10.webp',
    event_website: 'https://www.example.com/bunny-bonding-brunch',
    audience: 'Rabbit Owners',
    creator_id: 10,
  },
  {
    id: 11,
    title: 'Pets & Paints Art Workshop',
    date: '2024-12-09',
    time: '14:00',
    location: 'Creative Studio, 890 Art Avenue, Pet City',
    description:
      '🎨🐾 Unleash your creativity at our Pets & Paints Art Workshop! Create beautiful pet portraits or abstract art with guidance from local artists. All materials provided, and pets are welcome!',
    event_image: 'event-11.webp',
    event_website: 'https://www.example.com/pets-paints-workshop',
    audience: 'Art Lovers and Pet Owners',
    creator_id: 11,
  },
  {
    id: 12,
    title: 'Pet Winter Wonderland',
    date: '2024-12-16',
    time: '13:00',
    location: 'Snowy Park, 234 Frosty Lane, Winterville',
    description:
      '❄️🐕 Celebrate the winter season with your pets at our Pet Winter Wonderland! Enjoy snow-themed games, hot cocoa for humans, and festive pet treats in a winter wonderland setting.',
    event_image: 'event-12.webp',
    event_website: 'https://www.example.com/pet-winter-wonderland',
    audience: 'Pet Owners',
    creator_id: 12,
  },
]

export async function seed(knex) {
  await knex('events').insert(addEvents)
}
